"""Target county definitions for data center site expansion.

Each entry describes a target county with known data sources.
ArcGIS URLs discovered automatically by discover_sources.py.
"""

TARGET_COUNTIES = {
    # ── NC: Charlotte metro (already have Mecklenburg, Union, York) ──
    "CABARRUS": {
        "state": "NC",
        "fips": "37025",
        "metro": "Charlotte",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 1,
    },
    "ROWAN": {
        "state": "NC",
        "fips": "37159",
        "metro": "Charlotte",
        "arcgis_url": "https://gis.rowancountync.gov/arcgis/rest/services",
        "nconemap_ok": True,
        "priority": 2,
    },
    "IREDELL": {
        "state": "NC",
        "fips": "37097",
        "metro": "Charlotte",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 3,
    },
    # ── NC: RTP / Triangle ──
    "DURHAM": {
        "state": "NC",
        "fips": "37063",
        "metro": "RTP",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 1,
    },
    "ORANGE_NC": {
        "state": "NC",
        "fips": "37135",
        "metro": "RTP",
        "county_name": "Orange",
        "arcgis_url": "https://gis.orangecountync.gov/arcgis/rest/services",
        "nconemap_ok": True,
        "priority": 2,
    },
    "JOHNSTON": {
        "state": "NC",
        "fips": "37101",
        "metro": "RTP",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 3,
    },
    "CHATHAM": {
        "state": "NC",
        "fips": "37037",
        "metro": "RTP",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 4,
    },
    # ── NC: Triad ──
    "GUILFORD": {
        "state": "NC",
        "fips": "37081",
        "metro": "Triad",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 1,
    },
    "FORSYTH": {
        "state": "NC",
        "fips": "37067",
        "metro": "Triad",
        "arcgis_url": None,
        "nconemap_ok": True,
        "priority": 2,
    },
    # ── SC ──
    "GREENVILLE": {
        "state": "SC",
        "fips": "45045",
        "metro": "Greenville",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 1,
    },
    "SPARTANBURG": {
        "state": "SC",
        "fips": "45083",
        "metro": "Greenville",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 2,
    },
    "CHARLESTON": {
        "state": "SC",
        "fips": "45019",
        "metro": "Charleston",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 3,
    },
    "BERKELEY": {
        "state": "SC",
        "fips": "45015",
        "metro": "Charleston",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 4,
    },
    "RICHLAND": {
        "state": "SC",
        "fips": "45079",
        "metro": "Columbia",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 5,
    },
    "LEXINGTON": {
        "state": "SC",
        "fips": "45063",
        "metro": "Columbia",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 6,
    },
    # ── GA: Atlanta metro ──
    "FULTON": {
        "state": "GA",
        "fips": "13121",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 1,
    },
    "DEKALB": {
        "state": "GA",
        "fips": "13089",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 2,
    },
    "COBB": {
        "state": "GA",
        "fips": "13067",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 3,
    },
    "GWINNETT": {
        "state": "GA",
        "fips": "13135",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 4,
    },
    "CHEROKEE": {
        "state": "GA",
        "fips": "13057",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 5,
    },
    "HENRY": {
        "state": "GA",
        "fips": "13151",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 6,
    },
    "FORSYTH": {
        "state": "GA",
        "fips": "13117",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 7,
    },
    "DOUGLAS": {
        "state": "GA",
        "fips": "13097",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 8,
    },
    "PAULDING": {
        "state": "GA",
        "fips": "13223",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 9,
    },
    "BARTOW": {
        "state": "GA",
        "fips": "13015",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 10,
    },
    "COWETA": {
        "state": "GA",
        "fips": "13077",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 11,
    },
    "FAYETTE": {
        "state": "GA",
        "fips": "13113",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 12,
    },
    "NEWTON": {
        "state": "GA",
        "fips": "13217",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 13,
    },
    "ROCKDALE": {
        "state": "GA",
        "fips": "13247",
        "metro": "Atlanta",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 14,
    },
    # ── FL ──
    "DUVAL": {
        "state": "FL",
        "fips": "12031",
        "metro": "Jacksonville",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 1,
    },
    "ORANGE_FL": {
        "state": "FL",
        "fips": "12095",
        "metro": "Orlando",
        "county_name": "Orange",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 2,
    },
    "SEMINOLE": {
        "state": "FL",
        "fips": "12117",
        "metro": "Orlando",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 3,
    },
    "OSCEOLA": {
        "state": "FL",
        "fips": "12097",
        "metro": "Orlando",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 4,
    },
    "HILLSBOROUGH": {
        "state": "FL",
        "fips": "12057",
        "metro": "Tampa",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 5,
    },
    "PINELLAS": {
        "state": "FL",
        "fips": "12103",
        "metro": "Tampa",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 6,
    },
    "MIAMI-DADE": {
        "state": "FL",
        "fips": "12086",
        "metro": "Miami",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 7,
    },
    "BROWARD": {
        "state": "FL",
        "fips": "12011",
        "metro": "Miami",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 8,
    },
    "PALM BEACH": {
        "state": "FL",
        "fips": "12099",
        "metro": "Miami",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 9,
    },
    "POLK": {
        "state": "FL",
        "fips": "12105",
        "metro": "Lakeland",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 10,
    },
    # ── VA ──
    "LOUDOUN": {
        "state": "VA",
        "fips": "51107",
        "metro": "NoVA",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 1,
    },
    "FAIRFAX": {
        "state": "VA",
        "fips": "51059",
        "metro": "NoVA",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 2,
    },
    "PRINCE WILLIAM": {
        "state": "VA",
        "fips": "51153",
        "metro": "NoVA",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 3,
    },
    "FAUQUIER": {
        "state": "VA",
        "fips": "51061",
        "metro": "NoVA",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 4,
    },
    "HENRICO": {
        "state": "VA",
        "fips": "51087",
        "metro": "Richmond",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 5,
    },
    "CHESTERFIELD": {
        "state": "VA",
        "fips": "51041",
        "metro": "Richmond",
        "arcgis_url": None,
        "nconemap_ok": False,
        "priority": 6,
    },
}
